### ISSUE TITLE
PIP-006: No motivation for mentee

### ISSUE THREAD

**Issue by troggy** [parsec-labs/PIPs#3]
> In the first 4 weeks the Mentee can claim half basic income without tacos.

It means mentee has low/no motivation to progress. Also "hit&run" possible

**Comment by johannbarbie** [comment]
that is right. for the mentor there is a high opportunity cost though. because he will not receive a reward for that mentee, and he is loosing 8 weeks

**Comment by troggy** [comment]
there is zero risk for mentor as well

**Comment by johannbarbie** [comment]
> A reward of 500,000 Parsec tokens is payed to the mentor of the graduating mentee.

that is right, no risk, just opportunity cost. he could have brought in a better mentee, which would have given him a reward.

should we add a deposit? 500,000 Parsec tokens deposit, if mentee does not graduate, tokens gone?

**Comment by troggy** [comment]
we are talking about incentive for mentor to do better mentee selection, right?

How about this:
Positive incentive: you get the $$ in the end if your mentee stick
Negative incentive: you will waste your time mentoring the guy who didn't stick.

No need for deposit imho. It is too complicated

**Comment by troggy** [comment]
The only uncovered scenario is when mentor is slacking. We have no way to incentivize in such situation except holding his deposit. But again it would be difficult to judge

**Comment by johannbarbie** [comment]
```
How about this:
Positive incentive: you get the $$ in the end if your mentee stick
Negative incentive: you will waste your time mentoring the guy who didn't stick.
```

that is exactly what i wanted to write down in the PIP. does it sound like something else?

**Comment by troggy** [comment]
I guess not, I was confiused with "he is loosing 8 weeks". 
Anyway, the original issue was about the lack of correct incentive for mentee. I would start with income for taco right away. Do you think it won't work?
